export const ICON_NAMES = {
  done: 'check',
  star: 'star',
  book: 'book',
  close: 'close',
  back: 'chevron-left',
  more: 'chevron-down',
  hide: 'chevron-up',
  passwordHidden: 'eye-lock',
  passwordShown: 'eye-lock-open',
  shimmer: 'shimmer',
  audio: 'volume-high',
  flag: 'flag',
  timer: 'clock-o',
  addFriend: 'account-plus-outline',
  addedFriend: 'account-check-outline',
  mistake: 'repeat-variant',
  settings: 'cog',
  turtle: 'tortoise',
  flagShtock: 'flag',
  circleDone: 'check-circle',
  circleClose: 'close-circle',
};
